### ISSUE TITLE
Rename to FSharp.Data.DynamoDB?

### ISSUE THREAD

**Issue by dsyme** [eiriktsarpalis/FSharp.AWS.DynamoDB#1]
Great to see! Now following this. Just say if you want to transfer to fsprojects.

I suppose this will eventually need a two-level namespace name to follow the [guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html), e.g.

    FSharp.Data.DynamoDB

Cheers!
Don

**Comment by eiriktsarpalis** [comment]
Hi Don,

I was thinking about the same, but potentially using FSharp.AWS.DynamoDB instead. This also follows what FSharp.Azure.Storage is doing.

**Comment by dsyme** [comment]
Ok, majes sense

**Comment by eiriktsarpalis** [comment]
Project has been renamed to FSharp.AWS.DynamoDB
